/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ContainerImageSourceApplyConfiguration represents a declarative configuration of the ContainerImageSource type for use
// with apply.
//
// ContainerImageSource defines a container image source.
type ContainerImageSourceApplyConfiguration struct {
	// Ref is the container image containing the MCP server implementation.
	// Must be a valid OCI image reference.
	// Examples:
	// - ghcr.io/modelcontextprotocol/servers/filesystem:latest
	// - ghcr.io/modelcontextprotocol/servers/github:v1.0.0
	// - custom-registry.io/my-mcp-server:1.2.3
	// - custom-registry.io/my-mcp-server@sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
	Ref *string `json:"ref,omitempty"`
	// PullPolicy controls when the kubelet pulls the MCP server image.
	// When omitted, Kubernetes applies its native default based on the image reference.
	PullPolicy *v1.PullPolicy `json:"pullPolicy,omitempty"`
	// ImagePullSecrets references Secrets in the MCPServer namespace that contain
	// credentials for pulling the MCP server image from a private registry.
	// The operator passes these references to the managed Pod and does not read
	// or copy Secret data.
	ImagePullSecrets []v1.LocalObjectReference `json:"imagePullSecrets,omitempty"`
}

// ContainerImageSourceApplyConfiguration constructs a declarative configuration of the ContainerImageSource type for use with
// apply.
func ContainerImageSource() *ContainerImageSourceApplyConfiguration {
	return &ContainerImageSourceApplyConfiguration{}
}

// WithRef sets the Ref field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ref field is set to the value of the last call.
func (b *ContainerImageSourceApplyConfiguration) WithRef(value string) *ContainerImageSourceApplyConfiguration {
	b.Ref = &value
	return b
}

// WithPullPolicy sets the PullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PullPolicy field is set to the value of the last call.
func (b *ContainerImageSourceApplyConfiguration) WithPullPolicy(value v1.PullPolicy) *ContainerImageSourceApplyConfiguration {
	b.PullPolicy = &value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *ContainerImageSourceApplyConfiguration) WithImagePullSecrets(values ...v1.LocalObjectReference) *ContainerImageSourceApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}
