/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MCPConfigApplyConfiguration represents a declarative configuration of the MCPConfig type for use
// with apply.
//
// MCPConfig defines Model Context Protocol specific properties of the server.
// This section captures how the server behaves as an MCP server, such as whether
// it maintains session state. These properties are distinct from container configuration
// (config), deployment management (runtime), and image sourcing (source).
type MCPConfigApplyConfiguration struct {
	// Stateless indicates whether the MCP server is stateless (does not maintain session state).
	// Only set this to true if the MCP server you are deploying declares that it is stateless.
	// When true, the generated Service uses SessionAffinity "None", allowing
	// requests to be freely load-balanced across replicas.
	// When false or unset, the Service uses SessionAffinity "ClientIP" so that
	// a given client's requests are routed to the same pod.
	// Defaults to false (stateful).
	Stateless *bool `json:"stateless,omitempty"`
}

// MCPConfigApplyConfiguration constructs a declarative configuration of the MCPConfig type for use with
// apply.
func MCPConfig() *MCPConfigApplyConfiguration {
	return &MCPConfigApplyConfiguration{}
}

// WithStateless sets the Stateless field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Stateless field is set to the value of the last call.
func (b *MCPConfigApplyConfiguration) WithStateless(value bool) *MCPConfigApplyConfiguration {
	b.Stateless = &value
	return b
}
