/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MCPGatewayBindingSpecApplyConfiguration represents a declarative configuration of the MCPGatewayBindingSpec type for use
// with apply.
//
// MCPGatewayBindingSpec defines the desired state of MCPGatewayBinding.
type MCPGatewayBindingSpecApplyConfiguration struct {
	// MCPServerRef is the name of the MCPServer resource in the same namespace
	// that this binding is for.
	MCPServerRef *string `json:"mcpServerRef,omitempty"`
	// Provider identifies which integration controller should handle this binding.
	// Integration controllers filter on this field to only process bindings they own.
	// Example: "httproute" for the reference Gateway API HTTPRoute controller.
	Provider *string `json:"provider,omitempty"`
	// ConfigRef is the name of a ConfigMap in the same namespace containing
	// provider-specific configuration.
	ConfigRef *string `json:"configRef,omitempty"`
}

// MCPGatewayBindingSpecApplyConfiguration constructs a declarative configuration of the MCPGatewayBindingSpec type for use with
// apply.
func MCPGatewayBindingSpec() *MCPGatewayBindingSpecApplyConfiguration {
	return &MCPGatewayBindingSpecApplyConfiguration{}
}

// WithMCPServerRef sets the MCPServerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MCPServerRef field is set to the value of the last call.
func (b *MCPGatewayBindingSpecApplyConfiguration) WithMCPServerRef(value string) *MCPGatewayBindingSpecApplyConfiguration {
	b.MCPServerRef = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *MCPGatewayBindingSpecApplyConfiguration) WithProvider(value string) *MCPGatewayBindingSpecApplyConfiguration {
	b.Provider = &value
	return b
}

// WithConfigRef sets the ConfigRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigRef field is set to the value of the last call.
func (b *MCPGatewayBindingSpecApplyConfiguration) WithConfigRef(value string) *MCPGatewayBindingSpecApplyConfiguration {
	b.ConfigRef = &value
	return b
}
