/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MCPGatewayBindingStatusApplyConfiguration represents a declarative configuration of the MCPGatewayBindingStatus type for use
// with apply.
//
// MCPGatewayBindingStatus defines the observed state of MCPGatewayBinding.
type MCPGatewayBindingStatusApplyConfiguration struct {
	// URL is the gateway endpoint URL, set by the integration controller.
	// The MCPServer reconciler reflects this into MCPServer status.
	URL *string `json:"url,omitempty"`
	// Conditions represent the latest available observations of the binding's state.
	//
	// Standard condition types:
	// - "Registered": The integration controller has processed this binding
	// and created the necessary gateway resources.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MCPGatewayBindingStatusApplyConfiguration constructs a declarative configuration of the MCPGatewayBindingStatus type for use with
// apply.
func MCPGatewayBindingStatus() *MCPGatewayBindingStatusApplyConfiguration {
	return &MCPGatewayBindingStatusApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *MCPGatewayBindingStatusApplyConfiguration) WithURL(value string) *MCPGatewayBindingStatusApplyConfiguration {
	b.URL = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MCPGatewayBindingStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MCPGatewayBindingStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
