/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MCPServerCapabilitiesApplyConfiguration represents a declarative configuration of the MCPServerCapabilities type for use
// with apply.
//
// MCPServerCapabilities describes which MCP protocol capabilities the server advertises
// during the initialize handshake.
type MCPServerCapabilitiesApplyConfiguration struct {
	// Tools indicates the server supports tool listing and invocation.
	Tools *bool `json:"tools,omitempty"`
	// Resources indicates the server supports resource listing and reading.
	Resources *bool `json:"resources,omitempty"`
	// Prompts indicates the server supports prompt templates.
	Prompts *bool `json:"prompts,omitempty"`
	// Logging indicates the server supports sending log messages.
	Logging *bool `json:"logging,omitempty"`
	// Completions indicates the server supports argument autocompletion.
	Completions *bool `json:"completions,omitempty"`
}

// MCPServerCapabilitiesApplyConfiguration constructs a declarative configuration of the MCPServerCapabilities type for use with
// apply.
func MCPServerCapabilities() *MCPServerCapabilitiesApplyConfiguration {
	return &MCPServerCapabilitiesApplyConfiguration{}
}

// WithTools sets the Tools field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tools field is set to the value of the last call.
func (b *MCPServerCapabilitiesApplyConfiguration) WithTools(value bool) *MCPServerCapabilitiesApplyConfiguration {
	b.Tools = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *MCPServerCapabilitiesApplyConfiguration) WithResources(value bool) *MCPServerCapabilitiesApplyConfiguration {
	b.Resources = &value
	return b
}

// WithPrompts sets the Prompts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prompts field is set to the value of the last call.
func (b *MCPServerCapabilitiesApplyConfiguration) WithPrompts(value bool) *MCPServerCapabilitiesApplyConfiguration {
	b.Prompts = &value
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *MCPServerCapabilitiesApplyConfiguration) WithLogging(value bool) *MCPServerCapabilitiesApplyConfiguration {
	b.Logging = &value
	return b
}

// WithCompletions sets the Completions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Completions field is set to the value of the last call.
func (b *MCPServerCapabilitiesApplyConfiguration) WithCompletions(value bool) *MCPServerCapabilitiesApplyConfiguration {
	b.Completions = &value
	return b
}
