/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MCPServerInfoApplyConfiguration represents a declarative configuration of the MCPServerInfo type for use
// with apply.
//
// MCPServerInfo contains identity and capability information reported by the
// MCP server during the protocol initialize handshake.
type MCPServerInfoApplyConfiguration struct {
	// Name is the server's self-reported name.
	Name *string `json:"name,omitempty"`
	// Version is the server's self-reported version.
	Version *string `json:"version,omitempty"`
	// ProtocolVersion is the MCP protocol version negotiated during the handshake.
	ProtocolVersion *string `json:"protocolVersion,omitempty"`
	// Instructions describes how to use the server and its features.
	// This can be used by clients to improve the LLM's understanding of
	// available tools, resources, etc.
	Instructions *string `json:"instructions,omitempty"`
	// Capabilities lists which MCP protocol features the server supports.
	Capabilities *MCPServerCapabilitiesApplyConfiguration `json:"capabilities,omitempty"`
}

// MCPServerInfoApplyConfiguration constructs a declarative configuration of the MCPServerInfo type for use with
// apply.
func MCPServerInfo() *MCPServerInfoApplyConfiguration {
	return &MCPServerInfoApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MCPServerInfoApplyConfiguration) WithName(value string) *MCPServerInfoApplyConfiguration {
	b.Name = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *MCPServerInfoApplyConfiguration) WithVersion(value string) *MCPServerInfoApplyConfiguration {
	b.Version = &value
	return b
}

// WithProtocolVersion sets the ProtocolVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtocolVersion field is set to the value of the last call.
func (b *MCPServerInfoApplyConfiguration) WithProtocolVersion(value string) *MCPServerInfoApplyConfiguration {
	b.ProtocolVersion = &value
	return b
}

// WithInstructions sets the Instructions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instructions field is set to the value of the last call.
func (b *MCPServerInfoApplyConfiguration) WithInstructions(value string) *MCPServerInfoApplyConfiguration {
	b.Instructions = &value
	return b
}

// WithCapabilities sets the Capabilities field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capabilities field is set to the value of the last call.
func (b *MCPServerInfoApplyConfiguration) WithCapabilities(value *MCPServerCapabilitiesApplyConfiguration) *MCPServerInfoApplyConfiguration {
	b.Capabilities = value
	return b
}
