/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MCPServerAddressApplyConfiguration represents a declarative configuration of the MCPServerAddress type for use
// with apply.
//
// MCPServerAddress contains the address information for the MCPServer.
type MCPServerAddressApplyConfiguration struct {
	// URL is the cluster-internal address of the MCP server service.
	// Format: <scheme>://<servicename>.<namespace>.svc.cluster.local:<port>/<path>
	// The scheme is "https" when TLS is enabled, "http" otherwise.
	URL *string `json:"url,omitempty"`
}

// MCPServerAddressApplyConfiguration constructs a declarative configuration of the MCPServerAddress type for use with
// apply.
func MCPServerAddress() *MCPServerAddressApplyConfiguration {
	return &MCPServerAddressApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *MCPServerAddressApplyConfiguration) WithURL(value string) *MCPServerAddressApplyConfiguration {
	b.URL = &value
	return b
}
