/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ServerConfigApplyConfiguration represents a declarative configuration of the ServerConfig type for use
// with apply.
//
// ServerConfig defines how the MCP server should be configured when it runs.
type ServerConfigApplyConfiguration struct {
	// Port is a required field that specifies the port number on which the MCP server listens for connections.
	// Must be between 1 and 65535.
	// This should match the port that the MCP server container exposes and will be used for
	// configuring the Kubernetes Service.
	Port *int32 `json:"port,omitempty"`
	// Arguments are command line arguments for the MCP server container.
	// Use this to pass configuration flags to the server.
	// Example: ["--config", "/etc/mcp-config/config.toml", "--verbose"]
	// When not specified, the container image's default arguments (CMD/ENTRYPOINT) are used.
	// Empty strings within the array are not allowed.
	Arguments []string `json:"arguments,omitempty"`
	// Env is a list of environment variables to set in the MCP server container.
	// Supports the full Kubernetes EnvVar API including valueFrom for secrets and configmaps.
	Env []v1.EnvVar `json:"env,omitempty"`
	// EnvFrom is a list of sources to populate environment variables in the MCP server container.
	// Each entry injects all key-value pairs from a Secret or ConfigMap as environment variables.
	// The keys become the variable names. Useful when a Secret's keys already match
	// the expected env var names (e.g., GITHUB_TOKEN).
	EnvFrom []v1.EnvFromSource `json:"envFrom,omitempty"`
	// Storage defines storage mounts for ConfigMaps, Secrets, and EmptyDirs.
	// Each item uses native Kubernetes volume source types for consistency and feature parity.
	// If specified, must contain at least 1 item. Maximum 64 items.
	// Each storage mount must have a unique path.
	Storage []StorageMountApplyConfiguration `json:"storage,omitempty"`
	// Path is the HTTP path where the MCP server listens for SSE/Streamable HTTP connections.
	// This path is appended to the service address in the status URL.
	// Must be a valid URI path component starting with '/'.
	// Maximum 253 characters. Cannot contain spaces, control characters, or query/fragment separators (? #).
	// Examples: /mcp, /api/v1/mcp, /services/mcp-server
	// Defaults to /mcp if not specified.
	Path *string `json:"path,omitempty"`
}

// ServerConfigApplyConfiguration constructs a declarative configuration of the ServerConfig type for use with
// apply.
func ServerConfig() *ServerConfigApplyConfiguration {
	return &ServerConfigApplyConfiguration{}
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ServerConfigApplyConfiguration) WithPort(value int32) *ServerConfigApplyConfiguration {
	b.Port = &value
	return b
}

// WithArguments adds the given value to the Arguments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Arguments field.
func (b *ServerConfigApplyConfiguration) WithArguments(values ...string) *ServerConfigApplyConfiguration {
	for i := range values {
		b.Arguments = append(b.Arguments, values[i])
	}
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *ServerConfigApplyConfiguration) WithEnv(values ...v1.EnvVar) *ServerConfigApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithEnvFrom adds the given value to the EnvFrom field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EnvFrom field.
func (b *ServerConfigApplyConfiguration) WithEnvFrom(values ...v1.EnvFromSource) *ServerConfigApplyConfiguration {
	for i := range values {
		b.EnvFrom = append(b.EnvFrom, values[i])
	}
	return b
}

// WithStorage adds the given value to the Storage field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Storage field.
func (b *ServerConfigApplyConfiguration) WithStorage(values ...*StorageMountApplyConfiguration) *ServerConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithStorage")
		}
		b.Storage = append(b.Storage, *values[i])
	}
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ServerConfigApplyConfiguration) WithPath(value string) *ServerConfigApplyConfiguration {
	b.Path = &value
	return b
}
