/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TransportConfigApplyConfiguration represents a declarative configuration of the TransportConfig type for use
// with apply.
//
// TransportConfig configures transport-layer settings for
// operator-to-MCP-server communication.
type TransportConfigApplyConfiguration struct {
	// TLS configures TLS for operator-to-MCP-server communication
	// during handshake and discovery probes.
	TLS *TLSClientConfigApplyConfiguration `json:"tls,omitempty"`
}

// TransportConfigApplyConfiguration constructs a declarative configuration of the TransportConfig type for use with
// apply.
func TransportConfig() *TransportConfigApplyConfiguration {
	return &TransportConfigApplyConfiguration{}
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *TransportConfigApplyConfiguration) WithTLS(value *TLSClientConfigApplyConfiguration) *TransportConfigApplyConfiguration {
	b.TLS = value
	return b
}
