FROM registry.redhat.io/ubi9/go-toolset@sha256:0a4666f7a4eb0644c97a73cba198eb268691b270d97831822689e7a2088f87be AS builder
ARG TARGETOS
ARG TARGETARCH
ARG TARGETPLATFORM

USER 0
WORKDIR /workspace
COPY . .

ENV GOEXPERIMENT=strictfipsruntime
ENV GOTOOLCHAIN=local
RUN make -f Makefile-ocp.mk build-ocp GO_BUILD_ENV="GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH}"

FROM --platform=$TARGETPLATFORM registry.redhat.io/ubi9/ubi-minimal@sha256:beeada7dd17903dfb69fd5f6916c054720bf28a52daaa2f7a1910a1394244bd2 AS crypto-policy
RUN microdnf install -y crypto-policies-scripts && \
    update-crypto-policies --set DEFAULT:PQ --no-reload

FROM --platform=$TARGETPLATFORM registry.redhat.io/ubi9/ubi-minimal@sha256:beeada7dd17903dfb69fd5f6916c054720bf28a52daaa2f7a1910a1394244bd2
COPY --from=crypto-policy /etc/crypto-policies /etc/crypto-policies
WORKDIR /
COPY --from=builder /workspace/manager .
RUN mkdir /licenses
COPY --from=builder /workspace/LICENSE /licenses/

USER 65532:65532

# Labels for enterprise contract
LABEL com.redhat.component=mcp-lifecycle-operator
LABEL cpe="cpe:/a:redhat:mcp_lifecycle_operator:0.1::el9"
LABEL description="MCP lifecycle operator"
LABEL io.k8s.description="MCP lifecycle operator"
LABEL io.k8s.display-name="MCP lifecycle operator"
LABEL io.openshift.tags="openshift,mcp,operator"
LABEL name="mcp-lifecycle-operator-beta/mcp-lifecycle-rhel9-operator"
LABEL release=0.1.0
LABEL url="https://github.com/opendatahub-io/mcp-lifecycle-operator"
LABEL vendor="Red Hat, Inc."
LABEL version=0.1.0
LABEL summary="MCP lifecycle operator"

ENTRYPOINT ["/manager"]
