apiVersion: mcp.x-k8s.io/v1alpha1
kind: MCPServer
metadata:
  name: everything-mcp-server
  namespace: default
spec:
  source:
    type: ContainerImage
    containerImage:
      ref: quay.io/matzew/mcp-everything:2026.7.10
  config:
    port: 3001
    path: /mcp
