/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

// GatewayBindingStatusApplyConfiguration represents a declarative configuration of the GatewayBindingStatus type for use
// with apply.
//
// GatewayBindingStatus contains the status of the MCPGatewayBinding
// created for this MCPServer.
type GatewayBindingStatusApplyConfiguration struct {
	// Name is the name of the MCPGatewayBinding resource.
	Name *string `json:"name,omitempty"`
	// Provider is the gateway integration provider handling this binding.
	Provider *string `json:"provider,omitempty"`
}

// GatewayBindingStatusApplyConfiguration constructs a declarative configuration of the GatewayBindingStatus type for use with
// apply.
func GatewayBindingStatus() *GatewayBindingStatusApplyConfiguration {
	return &GatewayBindingStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *GatewayBindingStatusApplyConfiguration) WithName(value string) *GatewayBindingStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *GatewayBindingStatusApplyConfiguration) WithProvider(value string) *GatewayBindingStatusApplyConfiguration {
	b.Provider = &value
	return b
}
