/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

// GatewaySpecApplyConfiguration represents a declarative configuration of the GatewaySpec type for use
// with apply.
//
// GatewaySpec configures gateway integration for an MCPServer.
type GatewaySpecApplyConfiguration struct {
	// Provider identifies which gateway integration controller should handle
	// this MCPServer. The operator creates an MCPGatewayBinding with this value
	// as spec.provider. Integration controllers filter bindings by provider name.
	// Example: "httproute" for the reference Gateway API HTTPRoute controller.
	Provider *string `json:"provider,omitempty"`
	// ConfigRef is the name of a ConfigMap in the same namespace containing
	// gateway-specific configuration. The ConfigMap is referenced by the
	// MCPGatewayBinding and read by the integration controller.
	ConfigRef *string `json:"configRef,omitempty"`
}

// GatewaySpecApplyConfiguration constructs a declarative configuration of the GatewaySpec type for use with
// apply.
func GatewaySpec() *GatewaySpecApplyConfiguration {
	return &GatewaySpecApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *GatewaySpecApplyConfiguration) WithProvider(value string) *GatewaySpecApplyConfiguration {
	b.Provider = &value
	return b
}

// WithConfigRef sets the ConfigRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigRef field is set to the value of the last call.
func (b *GatewaySpecApplyConfiguration) WithConfigRef(value string) *GatewaySpecApplyConfiguration {
	b.ConfigRef = &value
	return b
}
