/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// HealthConfigApplyConfiguration represents a declarative configuration of the HealthConfig type for use
// with apply.
//
// HealthConfig defines health check configuration for the MCP server.
// If not specified, no health probes will be configured.
//
// The probes are passed directly to the Deployment's container spec without any
// transformation, providing full access to the Kubernetes Probe API. This includes
// all probe types (httpGet, tcpSocket, exec, grpc) and all configuration options
// (initialDelaySeconds, periodSeconds, timeoutSeconds, successThreshold, failureThreshold).
type HealthConfigApplyConfiguration struct {
	// LivenessProbe defines the liveness probe for the MCP server container.
	// Kubernetes uses liveness probes to know when to restart a container.
	// If not specified, no liveness probe will be configured.
	//
	// This probe is passed directly to the container spec without transformation,
	// providing full compatibility with the Kubernetes Probe API.
	//
	LivenessProbe *v1.Probe `json:"livenessProbe,omitempty"`
	// ReadinessProbe defines the readiness probe for the MCP server container.
	// Kubernetes uses readiness probes to know when a container is ready to start accepting traffic.
	// If not specified, no readiness probe will be configured.
	//
	// This probe is passed directly to the container spec without transformation,
	// providing full compatibility with the Kubernetes Probe API.
	//
	ReadinessProbe *v1.Probe `json:"readinessProbe,omitempty"`
}

// HealthConfigApplyConfiguration constructs a declarative configuration of the HealthConfig type for use with
// apply.
func HealthConfig() *HealthConfigApplyConfiguration {
	return &HealthConfigApplyConfiguration{}
}

// WithLivenessProbe sets the LivenessProbe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LivenessProbe field is set to the value of the last call.
func (b *HealthConfigApplyConfiguration) WithLivenessProbe(value v1.Probe) *HealthConfigApplyConfiguration {
	b.LivenessProbe = &value
	return b
}

// WithReadinessProbe sets the ReadinessProbe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadinessProbe field is set to the value of the last call.
func (b *HealthConfigApplyConfiguration) WithReadinessProbe(value v1.Probe) *HealthConfigApplyConfiguration {
	b.ReadinessProbe = &value
	return b
}
