/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/networking/v1"
)

// NetworkConfigApplyConfiguration represents a declarative configuration of the NetworkConfig type for use
// with apply.
//
// NetworkConfig defines network policies for the MCP server pod.
type NetworkConfigApplyConfiguration struct {
	// IngressFrom restricts which sources can reach the MCP server port.
	// Uses standard Kubernetes NetworkPolicyPeer selectors (podSelector,
	// namespaceSelector, ipBlock).
	// When empty, any pod in the cluster can reach the MCP server (default).
	IngressFrom []v1.NetworkPolicyPeer `json:"ingressFrom,omitempty"`
	// EgressTo restricts which destinations the MCP server pod can reach.
	// Uses standard Kubernetes NetworkPolicyPeer selectors (podSelector,
	// namespaceSelector, ipBlock).
	// When empty, egress to all destinations is allowed (default).
	// DNS (UDP/TCP port 53) egress is always permitted regardless of this
	// setting.
	EgressTo []v1.NetworkPolicyPeer `json:"egressTo,omitempty"`
	// EgressPorts restricts which ports the MCP server pod can connect to.
	// When empty and EgressTo is set, all ports are allowed to the
	// specified destinations. When set, only listed ports are allowed
	// (in addition to DNS port 53 which is always permitted).
	EgressPorts []v1.NetworkPolicyPort `json:"egressPorts,omitempty"`
	// DNSEgressPeer scopes the automatically-added DNS (UDP/TCP port 53)
	// egress rule to a specific destination instead of allowing DNS to
	// any destination. Uses a standard Kubernetes NetworkPolicyPeer
	// selector (podSelector, namespaceSelector, ipBlock).
	// This field only takes effect when EgressTo or EgressPorts is set;
	// it does not by itself activate egress restrictions.
	// When EgressTo or EgressPorts is set and DNSEgressPeer is empty,
	// DNS egress remains permitted to any destination (default).
	DNSEgressPeer *v1.NetworkPolicyPeer `json:"dnsEgressPeer,omitempty"`
}

// NetworkConfigApplyConfiguration constructs a declarative configuration of the NetworkConfig type for use with
// apply.
func NetworkConfig() *NetworkConfigApplyConfiguration {
	return &NetworkConfigApplyConfiguration{}
}

// WithIngressFrom adds the given value to the IngressFrom field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IngressFrom field.
func (b *NetworkConfigApplyConfiguration) WithIngressFrom(values ...v1.NetworkPolicyPeer) *NetworkConfigApplyConfiguration {
	for i := range values {
		b.IngressFrom = append(b.IngressFrom, values[i])
	}
	return b
}

// WithEgressTo adds the given value to the EgressTo field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EgressTo field.
func (b *NetworkConfigApplyConfiguration) WithEgressTo(values ...v1.NetworkPolicyPeer) *NetworkConfigApplyConfiguration {
	for i := range values {
		b.EgressTo = append(b.EgressTo, values[i])
	}
	return b
}

// WithEgressPorts adds the given value to the EgressPorts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EgressPorts field.
func (b *NetworkConfigApplyConfiguration) WithEgressPorts(values ...v1.NetworkPolicyPort) *NetworkConfigApplyConfiguration {
	for i := range values {
		b.EgressPorts = append(b.EgressPorts, values[i])
	}
	return b
}

// WithDNSEgressPeer sets the DNSEgressPeer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSEgressPeer field is set to the value of the last call.
func (b *NetworkConfigApplyConfiguration) WithDNSEgressPeer(value v1.NetworkPolicyPeer) *NetworkConfigApplyConfiguration {
	b.DNSEgressPeer = &value
	return b
}
