/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// RuntimeConfigApplyConfiguration represents a declarative configuration of the RuntimeConfig type for use
// with apply.
//
// RuntimeConfig defines runtime execution configuration for the MCP server.
//
// This section covers how the MCP server executes and behaves at runtime,
// including replicas, security, resource allocation, and health probes.
//
// If not specified, default runtime settings will be applied.
// See individual field documentation for specific defaults.
type RuntimeConfigApplyConfiguration struct {
	// Replicas is the number of MCP server pod replicas to run.
	// Defaults to 1 if not specified.
	// Set to 0 to scale down the deployment.
	// This field is a pointer (*int32) to distinguish between:
	// - nil (not specified) -> defaults to 1 replica
	// - ptr.To(0) (explicit 0) -> scale-to-zero
	// This follows the same pattern as Deployment.Spec.Replicas in k8s.io/api/apps/v1.
	Replicas *int32 `json:"replicas,omitempty"`
	// Security defines security-related configuration.
	// If not specified, default security settings will be applied.
	Security *SecurityConfigApplyConfiguration `json:"security,omitempty"`
	// Resources defines the resource requirements for the MCP server container.
	// This includes CPU and memory requests and limits.
	// If not specified, the following defaults are applied:
	// - Requests: 50m CPU, 64Mi memory
	// - Limits: 500m CPU, 256Mi memory
	// Supports partial specification (e.g., only requests or only limits).
	// When partially specified, only the provided fields are used; defaults
	// are not merged into the unspecified fields.
	// Example:
	// resources:
	// requests:
	// cpu: "100m"
	// memory: "256Mi"
	// limits:
	// cpu: "500m"
	// memory: "512Mi"
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
	// Health defines health check configuration for the MCP server.
	// If not specified, no health probes will be configured.
	Health *HealthConfigApplyConfiguration `json:"health,omitempty"`
}

// RuntimeConfigApplyConfiguration constructs a declarative configuration of the RuntimeConfig type for use with
// apply.
func RuntimeConfig() *RuntimeConfigApplyConfiguration {
	return &RuntimeConfigApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *RuntimeConfigApplyConfiguration) WithReplicas(value int32) *RuntimeConfigApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithSecurity sets the Security field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Security field is set to the value of the last call.
func (b *RuntimeConfigApplyConfiguration) WithSecurity(value *SecurityConfigApplyConfiguration) *RuntimeConfigApplyConfiguration {
	b.Security = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *RuntimeConfigApplyConfiguration) WithResources(value v1.ResourceRequirements) *RuntimeConfigApplyConfiguration {
	b.Resources = &value
	return b
}

// WithHealth sets the Health field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Health field is set to the value of the last call.
func (b *RuntimeConfigApplyConfiguration) WithHealth(value *HealthConfigApplyConfiguration) *RuntimeConfigApplyConfiguration {
	b.Health = value
	return b
}
