/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// SecurityConfigApplyConfiguration represents a declarative configuration of the SecurityConfig type for use
// with apply.
//
// SecurityConfig defines security-related configuration.
// If not specified, default security settings will be applied.
// See individual field documentation for specific defaults.
type SecurityConfigApplyConfiguration struct {
	// ServiceAccountName is the name of the ServiceAccount to use for the MCP server pods.
	// The ServiceAccount should have appropriate RBAC permissions for the MCP server's operations.
	// If not specified, the default ServiceAccount for the namespace will be used.
	// Must be a string that follows the DNS1123 subdomain format.
	// Must be at most 253 characters in length, and must consist only of lower case alphanumeric characters, '-'
	// and '.', and must start and end with an alphanumeric character.
	// Example: For kubernetes-mcp-server with read-only access, create a ServiceAccount
	// and bind it to the 'view' ClusterRole.
	ServiceAccountName *string `json:"serviceAccountName,omitempty"`
	// PodSecurityContext specifies the security context for the MCP server pod.
	PodSecurityContext *v1.PodSecurityContext `json:"podSecurityContext,omitempty"`
	// SecurityContext specifies the security context for the MCP server container.
	SecurityContext *v1.SecurityContext `json:"securityContext,omitempty"`
}

// SecurityConfigApplyConfiguration constructs a declarative configuration of the SecurityConfig type for use with
// apply.
func SecurityConfig() *SecurityConfigApplyConfiguration {
	return &SecurityConfigApplyConfiguration{}
}

// WithServiceAccountName sets the ServiceAccountName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountName field is set to the value of the last call.
func (b *SecurityConfigApplyConfiguration) WithServiceAccountName(value string) *SecurityConfigApplyConfiguration {
	b.ServiceAccountName = &value
	return b
}

// WithPodSecurityContext sets the PodSecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSecurityContext field is set to the value of the last call.
func (b *SecurityConfigApplyConfiguration) WithPodSecurityContext(value v1.PodSecurityContext) *SecurityConfigApplyConfiguration {
	b.PodSecurityContext = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *SecurityConfigApplyConfiguration) WithSecurityContext(value v1.SecurityContext) *SecurityConfigApplyConfiguration {
	b.SecurityContext = &value
	return b
}
