/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	apiv1beta1 "github.com/kubernetes-sigs/mcp-lifecycle-operator/api/v1beta1"
)

// SourceApplyConfiguration represents a declarative configuration of the Source type for use
// with apply.
//
// Source defines where the MCP server's container image (or other source types in the future) is located.
type SourceApplyConfiguration struct {
	// Type is a required field that configures how the MCP server should be sourced.
	// Allowed values are: ContainerImage.
	// When set to ContainerImage, the MCP server will be sourced directly from an OCI
	// container image following the configuration specified in containerImage.
	Type *apiv1beta1.SourceType `json:"type,omitempty"`
	// ContainerImage specifies container image details when Type is ContainerImage.
	ContainerImage *ContainerImageSourceApplyConfiguration `json:"containerImage,omitempty"`
}

// SourceApplyConfiguration constructs a declarative configuration of the Source type for use with
// apply.
func Source() *SourceApplyConfiguration {
	return &SourceApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SourceApplyConfiguration) WithType(value apiv1beta1.SourceType) *SourceApplyConfiguration {
	b.Type = &value
	return b
}

// WithContainerImage sets the ContainerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerImage field is set to the value of the last call.
func (b *SourceApplyConfiguration) WithContainerImage(value *ContainerImageSourceApplyConfiguration) *SourceApplyConfiguration {
	b.ContainerImage = value
	return b
}
