/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	apiv1beta1 "github.com/kubernetes-sigs/mcp-lifecycle-operator/api/v1beta1"
)

// StorageMountApplyConfiguration represents a declarative configuration of the StorageMount type for use
// with apply.
//
// StorageMount defines a storage mount combining volume source and mount configuration.
// The Path and Permissions fields apply to all storage types, while Source contains
// the type-specific configuration (ConfigMap, Secret, or EmptyDir).
type StorageMountApplyConfiguration struct {
	// Path is a required field that specifies where the volume should be mounted in the container.
	// Must be an absolute path (starting with /).
	// The ConfigMap or Secret data will be accessible to the MCP server process at this location.
	// Must be between 1 and 4096 characters, start with '/', and must not contain ':'.
	Path *string `json:"path,omitempty"`
	// Permissions specifies the access permissions for the mount.
	// Allowed values are ReadOnly, ReadWrite, and RecursiveReadOnly.
	// When set to ReadOnly, the mount is read-only.
	// When set to ReadWrite, the mount is read-write.
	// When set to RecursiveReadOnly, the mount and all submounts are recursively read-only.
	// Defaults to ReadOnly for ConfigMap and Secret mounts.
	// For EmptyDir mounts, ReadWrite is more common for writable scratch space.
	Permissions *apiv1beta1.MountPermissions `json:"permissions,omitempty"`
	// Source defines where the storage data comes from (ConfigMap, Secret, or EmptyDir).
	Source *StorageSourceApplyConfiguration `json:"source,omitempty"`
}

// StorageMountApplyConfiguration constructs a declarative configuration of the StorageMount type for use with
// apply.
func StorageMount() *StorageMountApplyConfiguration {
	return &StorageMountApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *StorageMountApplyConfiguration) WithPath(value string) *StorageMountApplyConfiguration {
	b.Path = &value
	return b
}

// WithPermissions sets the Permissions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Permissions field is set to the value of the last call.
func (b *StorageMountApplyConfiguration) WithPermissions(value apiv1beta1.MountPermissions) *StorageMountApplyConfiguration {
	b.Permissions = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *StorageMountApplyConfiguration) WithSource(value *StorageSourceApplyConfiguration) *StorageMountApplyConfiguration {
	b.Source = value
	return b
}
